package io.nbe.squarly.model.generator;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link DungeonGenerator} specific assertions - Generated by CustomAssertionGenerator.
 */
public class DungeonGeneratorAssert extends AbstractAssert<DungeonGeneratorAssert, DungeonGenerator> {

  /**
   * Creates a new <code>{@link DungeonGeneratorAssert}</code> to make assertions on actual DungeonGenerator.
   * @param actual the DungeonGenerator we want to make assertions on.
   */
  public DungeonGeneratorAssert(DungeonGenerator actual) {
    super(actual, DungeonGeneratorAssert.class);
  }

  /**
   * An entry point for DungeonGeneratorAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myDungeonGenerator)</code> and get specific assertion with code completion.
   * @param actual the DungeonGenerator we want to make assertions on.
   * @return a new <code>{@link DungeonGeneratorAssert}</code>
   */
  public static DungeonGeneratorAssert assertThat(DungeonGenerator actual) {
    return new DungeonGeneratorAssert(actual);
  }

  /**
   * Verifies that the actual DungeonGenerator's gameGenerator is equal to the given one.
   * @param gameGenerator the given gameGenerator to compare the actual DungeonGenerator's gameGenerator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual DungeonGenerator's gameGenerator is not equal to the given one.
   */
  public DungeonGeneratorAssert hasGameGenerator(io.nbe.squarly.model.GameGenerator gameGenerator) {
    // check that actual DungeonGenerator we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting gameGenerator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    io.nbe.squarly.model.GameGenerator actualGameGenerator = actual.getGameGenerator();
    if (!Objects.areEqual(actualGameGenerator, gameGenerator)) {
      failWithMessage(assertjErrorMessage, actual, gameGenerator, actualGameGenerator);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual DungeonGenerator's mapWrapper is equal to the given one.
   * @param mapWrapper the given mapWrapper to compare the actual DungeonGenerator's mapWrapper to.
   * @return this assertion object.
   * @throws AssertionError - if the actual DungeonGenerator's mapWrapper is not equal to the given one.
   */
  public DungeonGeneratorAssert hasMapWrapper(io.nbe.squarly.model.generator.wrapper.GameMapWrapper mapWrapper) {
    // check that actual DungeonGenerator we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting mapWrapper of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    io.nbe.squarly.model.generator.wrapper.GameMapWrapper actualMapWrapper = actual.getMapWrapper();
    if (!Objects.areEqual(actualMapWrapper, mapWrapper)) {
      failWithMessage(assertjErrorMessage, actual, mapWrapper, actualMapWrapper);
    }

    // return the current assertion for method chaining
    return this;
  }

}
