package io.nbe.squarly.model.interfaces;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link IState} specific assertions - Generated by CustomAssertionGenerator.
 */
public class IStateAssert extends AbstractAssert<IStateAssert, IState> {

  /**
   * Creates a new <code>{@link IStateAssert}</code> to make assertions on actual IState.
   * @param actual the IState we want to make assertions on.
   */
  public IStateAssert(IState actual) {
    super(actual, IStateAssert.class);
  }

  /**
   * An entry point for IStateAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myIState)</code> and get specific assertion with code completion.
   * @param actual the IState we want to make assertions on.
   * @return a new <code>{@link IStateAssert}</code>
   */
  public static IStateAssert assertThat(IState actual) {
    return new IStateAssert(actual);
  }

}
