package io.nbe.squarly.model;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link PathFinder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class PathFinderAssert extends AbstractAssert<PathFinderAssert, PathFinder> {

  /**
   * Creates a new <code>{@link PathFinderAssert}</code> to make assertions on actual PathFinder.
   * @param actual the PathFinder we want to make assertions on.
   */
  public PathFinderAssert(PathFinder actual) {
    super(actual, PathFinderAssert.class);
  }

  /**
   * An entry point for PathFinderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPathFinder)</code> and get specific assertion with code completion.
   * @param actual the PathFinder we want to make assertions on.
   * @return a new <code>{@link PathFinderAssert}</code>
   */
  public static PathFinderAssert assertThat(PathFinder actual) {
    return new PathFinderAssert(actual);
  }

}
